README.md

Provide instructions to end-users who are not authenticated to Github via NPM

docs: ✏️  setup github npm registry access guideline

---

package.json
yarn.lock

DAB JS v4 Upgrade dfinity libraries to V10 [sc-24077]

---

README.md

Reordered docs, left empty space at the bottom so we add code examples on how to interact with the canister registry. Will replicate what we put here in the docs so plz add code examples in end-user format (async if async, etc.)

base v2 content update

---

package.json
yarn.lock

** BREAKING CHANGES **
dfinity package’s update could generate breaking changes

chore: update dfinity packages

---

package.json
src/constants/standards.ts
src/dab_canisters/nfts_registry.ts
src/idls/erc_721.did.ts
src/index.ts
src/interfaces/erc_721.ts
src/interfaces/nft.ts
src/nft_standards/departure_labs.ts
src/nft_standards/erc_721.ts
src/nft_standards/ext.ts
src/nft_standards/ic_punks.ts
yarn.lock

We need to implement a wrapper for ERC-721 NFT standard
TODO: define how we get the image

feat: implement wrapper for ERC-721

---

src/constants/index.ts
src/dab_canisters/canister_registry.ts
src/dab_canisters/nfts_registry.ts

** **BREAKING CHANGES** **
In order to make easier the use of dab-js methods we make optional agent argument where it is possible. And to make it more flexible we change all arguments for an object

feat: make optional agent argument for all methods

---

package.json
src/dab_canisters/canister_registry.ts

feat: implement get all

---

package.json
src/constants/index.ts
src/dab_canisters/nfts_registry.ts
yarn.lock

feat: user kyashu for caching get user NFTs

---

package.json
yarn.lock

Rollback - Agent 0.9

---

package.json
src/nft_standards/erc_721.ts

Serialize metadata as properties for plug to properly display them.

Added property formatting to metadata

---

package.json
src/dab_canisters/nfts_registry.ts

Changed crowns url with new canister holding correct attributes

---

src/constants/standards.ts
src/dab_canisters/index.ts
src/dab_canisters/nfts_registry.ts
src/dab_canisters/token_registry.ts
src/idls/dab_tokens.did.ts
src/idls/dip_20.did.ts
src/idls/wicp.did.ts
src/idls/xtc.did.ts
src/interfaces/dab_tokens.ts
src/interfaces/dip_20.ts
src/interfaces/ext.ts
src/interfaces/wicp.ts
src/interfaces/xtc.ts
src/nft_standards/departure_labs.ts
src/nft_standards/erc_721.ts
src/nft_standards/ext.ts
src/nft_standards/ic_punks.ts
src/token_standards/dip20Methods.ts
src/token_standards/extMethods.ts
src/token_standards/index.ts
src/token_standards/methods.ts
src/token_standards/wicpMethods.ts
src/token_standards/xtcMethods.ts
src/utils/actorFactory.ts

We add a wrapper for new token registry method of dab-js and create some wrapper for token like we did for NFTs before

feat: token registry

---

README.md

Updating --scope text for issue #50

---

package.json
src/interfaces/ext.ts
src/nft_standards/ext.ts
src/token_standards/extMethods.ts

Replaced `error` for `err` in ext interface file

Fix EXT interface file

---

package.json
src/constants/standards.ts
src/idls/dip_721_v2.did.ts
src/interfaces/dip_721_v2.ts
src/interfaces/nft.ts
src/registries/nfts_registry.ts
src/standard_wrappers/nft_standards/dip_721_v2.ts

feat: dip721v2

---

src/constants/standards.ts
src/idls/c3.did.ts
src/interfaces/c3.ts
src/interfaces/nft.ts
src/registries/nfts_registry.ts
src/standard_wrappers/nft_standards/ccc.ts

new feature to support C3 standard NFT, thanks for support. hope to have a deep cooperation with plug team.

new feature to support C3 standard NFT

---

package.json
src/standard_wrappers/token_standards/icpMethods.ts
src/utils/validations.ts

- Add account type validations
- Allow icp transfers directly to accountIds

Fix: send to account id

---

src/standard_wrappers/token_standards/icpMethods.ts

- Flipped condition as it was wrong.
- Removed unused line

Fix: send icp

---

package.json
src/idls/ext.did.ts

- Adds missing method to EXT token interface/

Fix: Add `extensions` to EXT token wrapper did file

---

package.json
src/standard_wrappers/nft_standards/dip_721_v2.ts

fix: dipv721v2 transfer

---

package.json
src/registries/nfts_registry.ts

Remove forced refresh on kyasshu

Removed forced refresh on kyasshu

---

package.json
src/standard_wrappers/nft_standards/dip_721.ts

- Added guard HOF to abstract backwards compatibility guards.
- Replaced current wards with HOF
- Added ward to `getMetadata` method.

Fix: DIP721 metadata

---

package.json
src/standard_wrappers/token_standards/rosettaMethods.ts

Changed principal validation to accept canisterIds

Fix: send ICP to canister ids

---

package.json
src/index.ts

- Export 0.9.3 `HttpAgent` and `Principal`

Added exports for 0.9.3 agent and principal

---

package.json
src/constants/standards.ts
src/registries/nfts_registry.ts

- Made NFT Standards uppercase.
- Removed nft error logs from production releases

Fix: Upper case nft standards.

---

package.json
src/utils/validations.ts

- Fix issue causing `isValidPrincipal` to throw when receiving a non-principal text.

Fix: isValidPrincipal
